import math
import numpy as np
import matplotlib.pyplot as plt

def power(t_minute,T_amb,T_0):
    k = -0.0327
    T=T_amb+(T_0-T_amb)*np.exp(k*t_minute)
    a = 83.06e-6
    return a*(T-T_amb)**2

t = np.linspace(0,30,100)
T_0 = 90
T_amb = 20
plt.plot(t,power(t,T_0,T_amb))
title = "Power generated by a thermoelectric generator module\n"
title = title + "GM250-127-10-15 by www.etdyn.com feeded by\n"
title = title + "800mL of water cooling from {0:d}°C to the ambient at {1:d}°C\n"
title = title + "and perfectly matched to a MPPT DC/DC converter"
plt.title(title.format(T_0,T_amb))
plt.xlabel('time in minutes')
plt.ylabel('power in watt')
plt.grid(True)
